import type { HomePageEditableContent } from "./homepage-content.types";

// This file is generated by scripts/markdown-to-homepage-content.ts.
// If needed, run:
// npm run generate:homepage-content -- --input /path/to/homepage-content.md
export const HOMEPAGE_EDITABLE_CONTENT: HomePageEditableContent = {};
